POST http://localhost:3000/workout
content-type: application/json

      {
        "type": "resistance",
        "name": "Military Press",
        "duration": 20,
        "weight": 300,
        "reps": 10,
        "sets": 4
      }
